# Generated by Django 3.2.4 on 2021-06-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humiture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=64)),
                ('Temperature', models.CharField(max_length=32)),
                ('Humidity', models.CharField(max_length=32)),
                ('Day', models.CharField(max_length=64)),
            ],
        ),
    ]
